services:
  - type: web
    name: online-marketplace-api
    runtime: node
    buildCommand: npx prisma generate && npm install && npm run build
    startCommand: npx prisma migrate deploy && npx prisma db seed && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: online-marketplace-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health

databases:
  - name: online-marketplace-db
    plan: free
    ipAllowList: []