services:
  - type: web
    name: online-marketplace-api
    runtime: node
    buildCommand: |
      npm i -g @nestjs/cli
      npm ci
      npx prisma generate
      npm run build
    preDeployCommand: |
      npx prisma migrate deploy
      NODE_ENV=production npx prisma db seed
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: online-marketplace-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health

databases:
  - name: online-marketplace-db
    plan: free
    ipAllowList: []
