name: Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecov:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test_db

      - name: Run tests with coverage
        run: npm run test:cov
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test_db
          JWT_SECRET: test_secret
          JWT_EXPIRES_IN: 1h
          JWT_REFRESH_SECRET: test_refresh_secret
          JWT_REFRESH_EXPIRES_IN: 7d
          CLOUDINARY_CLOUD_NAME: test_cloud
          CLOUDINARY_API_KEY: test_key
          CLOUDINARY_API_SECRET: test_secret

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
